language: python
python:
- '3.6'
sudo: false
branches:
  only:
  - master
install:
- pip install -r requirements.txt
jobs:
  include:
  - stage: Build Docker
    script: "./travis_scripts/docker-build.sh"
env:
  global:
  - secure: Hzz6U9+/hD2Jpb7Gv2EEvitOE6sCKai/k8GVskJRqtjL7ProWQG6fkD3pRekVdI0BTIAj65GSBmjy2BFe1q7IbuJLEik2MFqzvxC0IGN3VQYFAhEXoMyaK1zX5adZS+fu8INFB9NhT3yH1SH3vhRif+F5WrzdTZuFtA07U+KCe4g71PHpa8qt5T253UvH1IuLYnJNjhMLvmGFBtdvAIp+g8mmU8+q/TCYbS/YJlX/z/055w84II85Xn+nKZAUzOe0FkYL7WPACvOrj1Cw0uPxTlu9SAMA0ABV9eXiXhCw+LJkS9oCdBC4QkZ4KVc2VcnHuOALWmKIwrB3yFf0kvbtypWN6xg+48/X8Xxc5eFKCT1VaVYPSuH05NhVTHXpE0+DYzA0NJjLs6/cTLzPVHBB+HOZO7/Jm/PMhiTVFOeujSacobijOOxjsglT6rOHuwgttP6T6MVYLXstBV24KmrZc4da0crUO+jvR/uuHI3Xss6zeNHUQF/F4o/0zzQvKKxHBGjw8nDkGXgmHWgda/IVo4Y28kRbCD3v7PivTGqPnzE7WBIPSmk2J/qlv3p3XNNn2tl+M6pDxmZCAODhGB7DERafiPUgrtzTIrJozNv7uSuUJj1+6YJPQHUqbfwdq4PCqaMv6PTbBkGXMXVWM0KXKUxx0Z316jCS4kGiumPhZ0=
  - secure: VsftGRrsYRpJfJlpY6I5zBfC4ceS8SgScWCZTZemxRDaZEciB14Evk24SOCuPFjJRaUIwz8Elzhln31HeOqGnM0CMi5ckPuxg8sAWeUc87pfPGLxwickYYL73/EBEnVZJFU5sT+qC0OnVAXv7+mqJb6FwCDwc+CG/CffuOQ1U2I+6jncdpYxmFiXhEPcq4caBNR6DUljLt6YjnV+91b/39JvfqM0/5BHcHoPSPokzlB8OhI1Zg4OMDRO5vTciXpvoPOpVcK7Cu7lnkq1WjFctgv2aYuAi0uhboqbTgmEhnt5z3+q5GyYB8ieoy/d35rz1O+3zYX1WzlPWZBWcVZYnFxEogHjq2yvobPVVlwKiodpcVuTGv0UvOGOqYAI4Hh7ZAauF9hrB6Q1jG0hEb2bkhMY15OpYvLiV2vYFpxN7wE0oHV9Zik6ttJM9fIZRb1IQjOyF2/p5c0GMZFH3mHkKFVesEZuz+Fn6t/u72pZjy4zUiaOPpwKpog6pcehg8Hm3Gfs5GnN21LlnhlvAs5nP81rl0q7cc6R9IzWd4ph4LPl5TBBal/PdO0NaIrckQDFFduCKJ7dXpzA0448kR+STS3UZYmbgNZPJJYikQdzyJHX8EqnqOlU52V44kWg4lnMgDPPGcbbU2Vu53ai5zN76am0XSUt6IVsauEcYgG9iEs=
